spring.application.name=smarthr-backend
server.port=8080

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true

# JWT defaults ? overridden by profile
application.security.jwt.expiration=900000
application.security.jwt.refresh-expiration=604800000

