spring.application.name=smarthr-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/smarthr
spring.datasource.username=smarthr_user
spring.datasource.password=smarthr_pass

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

